### ISSUE TITLE
add a link to a card?

### ISSUE THREAD

**Issue by hankelvin** [treethought/flask-assistant#100]
Hi, is it possible to add a link to a card? If so, what's the parameter I should pass into resp.card() in order to input a url address? 

Thanks!

**Comment by 1337Phantom** [comment]
Hello,
You can add links by using the .link_out("Text","link") function
`resp.link_out("Text","https://example.com/")`
This will add a button reading Open Text to your card. For more information on how to use this read the documentation or have a look at the examples.

**Comment by hankelvin** [comment]
thanks for the reply @1337Phantom!
