### ISSUE TITLE
Creating google assistant app in python without flask assistant

### ISSUE THREAD

**Issue by umairkhan10** [treethought/flask-assistant#104]
I'm new on developing google assistant action. I've been creating skill on Alexa using lambda functions SDK where you link the lambda functions and intent handling using Skill ID and arn. You just make intents on Dev console and functions in lambda functions and skill works. I need to know a process where I can create action on google using similar approach. I don't want to use flask assistant. I know intents are made in Dialogflow and there is also cloud functions for actions but Is there any code sample or any other guide that I can look at ? I don't know the how to create

**Comment by treethought** [comment]
I haven't used it myself, but you might want to look at the docs for [creating a webhook](https://dialogflow.com/docs/fulfillment/configure) using the inline code editor.

**Comment by umairkhan10** [comment]
Yes, it's working on Node JS but there isn't any option of Python or any
otehr sample. I could use google cloud function as well but it isn't
working as well. I could send the request from dialogflow to cloud
function, can parse the data but can't send the response back to the
dialogflow.

**Comment by treethought** [comment]
I think you should be able to return an HTTP response to Dialogflow from
your cloud function.

Are you sure your webhook response is formatted correctly?
https://dialogflow.com/docs/fulfillment/how-it-works


umairkhan10 writes:

**Comment by disawalsagar** [comment]
Hi @umairkhan10 : Did you get resolution for above issue. I'm trying to use cloud functions, but not able to successfully get the response back.
