### ISSUE TITLE
match action by intent action instead of intent name.

### ISSUE THREAD

**Issue by sriramsv** [treethought/flask-assistant#11]
The matching by intent name is not ideal as intent names can be quite arbitrary in api.ai.
Matching by intent action would also mean we could use regex in the future to route particular requests according to intent action and group intents accordingly.

**Comment by treethought** [comment]
I have thought about matching via the action name and may be open to it. I haven't done so yet because it seems that action names are just as arbitrary as the corresponding intent names.

By grouping intents according to action, do you mean something like this?

```
@assist.action('IntentOne')
def action_a():
    return tell('You have triggered Action A with Intent One ')

@assist.action('IntentOne')
def action_b():
    return tell('You have triggered Action B with Intent One')

```

Currently, if you would like to route different action functions for the same intent you could do so with contexts, though this method is doesn't completely align with API.AI's context usage (see #8)


How would you imagine using regex to route requests to different actions?

**Comment by sriramsv** [comment]
No I envisioned it something like, task as the main module, task.A is a sub task and task B is another subtask. so imagining we have a plugin system which has files A.py and B.py in a module named task, it is easy to route to the file or function based on intent names.
Check (pluginbase)[http://pluginbase.pocoo.org/] module for more examples on this.

**Comment by treethought** [comment]
That's pretty interesting, I haven't seen pluginbase before. 
I can see how that could work for routing requests to functions, but would this offer any advantages aside from grouping actions into files?

I'll look more into pluginbase and maybe we could implement a plugin system to be used in addition to the current routing method. But I think the flask-style routing provides an easier entry for people new to the project, and should probably be kept.

As for grouping intents, [pluggable views](http://flask.pocoo.org/docs/0.12/views/) could possibly be another option

**Comment by sriramsv** [comment]
I agree flask style routing is very easy for people to get started, but eventually becomes messy to have hundreds of flask routes for each and every possible user action.
If we implement a plugin system, the plugin will be only loaded when a certain intent is matched and flask-assistant will generically handoff the request to the corresponding function or file containing all the logic which will handle that requests. This will application logic agnostic of any framework.
Imagining having a single function implementation which could serve both a flask endpoint or a flask-assistant intent without bothering which framework calls it.

**Comment by treethought** [comment]
I see, that could be pretty cool. I'll definitely look into it. Feel free to to try to put something together as well.

And thanks for bringing up these issues!
