### ISSUE TITLE
using multiple instances of an entity in schema yaml

### ISSUE THREAD

**Issue by RobbyKilgore** [treethought/flask-assistant#111]
I have an intent that uses two slots based on a single Entity. 
I'm not sure what the correct way to specify this in yaml would be...

my_intent:
  UserSays:
  -- "I want to go from Dumbo to Greenpoint"
  Annotation:
  -- Dumbo: stop:DepartingStop
  -- Greenpoint: stop:ArrivalStop

Unfortunately, I get an error that says that ':' is not the correct delimiter.
Is there a yaml/schema syntax that will allow me to specify parameter names that reference a shared entity as above?

**Comment by treethought** [comment]
closing as schema yaml definitions are no longer supported
