### ISSUE TITLE
Get user info

### ISSUE THREAD

**Issue by wtavares** [treethought/flask-assistant#115]
Hi, 

A very simple doubt: How can I can the user info comming from Google Assistant? 

I could see the the Assintant.request brings the user list and there is a userId coming from the request. 

There is a way to get another info like email?

Thanks in advance and congrats by the project... it is awesome!

**Comment by wtavares** [comment]
I believe that my answer is related with the comment at the end of isse #26 

But it's not clear to me how to do this exactly... someone know a howto or tutorial?

Also the userID will be deprecated... so here goes the actual way to configure the Actions:
https://developers.google.com/actions/identity/

**Comment by treethought** [comment]
Hi @wtavares thanks for the kind words.
You can now update to version 0.3.7 with `pip install -U flask-assistant` and access the user object by importing `user`.

Unfortunately it seems like the only user info provided is "lastSeen", "locale", userId (which will be deprecated), and any permissions granted.

However you can store information to be persisted across sessions in `user['userStorage']`.

And as for the soon-to-be deprecated userID, take a look at [Migrating to Webhook-generated IDs](https://developers.google.com/actions/identity/user-info). You can create your own unique ID and store in in userStorage.

```python
import uuid
from flask_assistant import ask, user

...

@assist.action('Default Welcome Intent')
def welcome():
    if user.get('userStorage') is None:
        user['userStorage'] = {}
        uid = uuid.uuid4()
        user['userStorage']['ID'] = str(uid)
        return ask('Looks like you're new here')
    
    elif user['userStorage'].get('ID') is not None:
        last_seen = user['lastSeen']
        return ask('welcome back! Haven't seen you since {}'.format(last_seen))
```

**Comment by diedezp** [comment]
Hi there, I just tried adding this snippet below to my script and it keeps returning else: error when I test it out in the simulator. Am I missing somthing? Thanks!

```python
from flask import Flask
from flask_assistant import Assistant, user, request, ask, tell, event
import uuid

...

@assist.action('Usersettings')
def usersettings():
    if user.get('userStorage') is None:
        user['userStorage'] = {}
        uid = uuid.uuid4()
        user['userStorage']['ID'] = str(uid)
        return ask('new here?')

    elif user['userStorage'].get('ID') is not None:
        return ask('welcome back!')

    else:
        return ask('error')
```

**Comment by davidalbertonogueira** [comment]
Same @diedezp . Storing a new generated uuid in user['userStorage'] is not working (no persistence). 
How should we operate @treethought ?

**Comment by treethought** [comment]
@diedezp @davidalbertonogueira due to the changes in how user storage is handled, you can now simply use the `storage` local.

using @diedezp's example, you would adapt it like so:

```python
from flask import Flask
from flask_assistant import Assistant, request, ask, tell, event, storage
import uuid

...

@assist.action("Usersettings")
def usersettings():
    if storage.get('ID') is None:
        uid = uuid.uuid4()
        storage['ID'] = str(uid)
        return ask('new here?')

    elif storage.get('ID') is not None:
        return ask('welcome back!')

    else:
        return ask('error')
```

**Comment by davidalbertonogueira** [comment]
@treethought I'm sorry, but using that code above, the storage variable is not saving the ID. Whenever I get a new request, storage is an empty dict.

**Comment by treethought** [comment]
hi @davidalbertonogueira i have seen a lot of reports with user storage not persisting on actions on google (across multiple clients/languages etc).

can you please take a look at [this comment](https://github.com/actions-on-google/codelabs-nodejs/issues/26#issuecomment-448519451) and ensure you have the proper options set in your google account? Unfortunately, User storage appears to only be applicable when the user has enabled "Include Chrome history..."

**Comment by davidalbertonogueira** [comment]
Hi @treethought . I already had a tick in "Include Chrome history", so that wouldn't fix it for me...

**Comment by davidalbertonogueira** [comment]
any news? @treethought

**Comment by Achyut4** [comment]
@treethought 

There are two definitions in flask_assistant "core.py" (class Assistant)

```
@property
    def user(self):
        return getattr(_app_ctx_stack.top, "_assist_user", {})

    @user.setter
    def user(self, value):
        storage_data = value.get("userStorage", {})

        if not isinstance(storage_data, dict):
            storage_data = json.loads(storage_data)

        value["userStorage"] = storage_data

        _app_ctx_stack.top._assist_user = value
        _app_ctx_stack.top._assist_storage = storage_data

    @property
    def storage(self):
        return self.user.get("userStorage", {})

    @storage.setter
    def storage(self, value):
        if not isintance(value, dict):
            raise TypeError("Storage must be a dictionary")

        self.user["userStorage"] = value
```
but none of them are storing user's data persistently, for every new session on the same user userStorage gets empty.
Hey @davidalbertonogueira  Any luck?
