### ISSUE TITLE
Cannot run gunicorn app locally but not after deployment to HEROKU

### ISSUE THREAD

**Issue by heymrlen** [treethought/flask-assistant#157]
I need help.  I understand that there were changes from using dialogflow to "google.cloud.dialogflow". I was able to fix this problem yesterday by simply downloading the zip file from this repo and replacing the one locally saved on my account. However, when I try to deploy it in HEROKU, it only install flask assistant version 0.5.2 which I believe does not have the updates from 3 months ago. Will git submodule works? If yes, how can I do it. I can't seem to figure it out. Any help will do? Thanks in advance!

**Comment by heymrlen** [comment]
I was able to solve this by downgrading the version of dialogflow to version 1.1.1 in my requirements.txt before pushing it to heroku

**Comment by treethought** [comment]
hi @heymrlen thank you for bringing these issues up. The changes for the diagflow update have not yet been released on pypi.

I will try to get a new release published tonight which should address your issues.
