### ISSUE TITLE
I found an issue.

### ISSUE THREAD

**Issue by opqrstu** [treethought/flask-assistant#2]
When I followed quick start guide, I got a small issue.
terminal :
> Traceback (most recent call last):
  File "my_assistant.py", line 2, in <module>
    from flask_assistant import Assistant, tell
  File "/home/opqrstu/anaconda3/lib/python3.5/site-packages/flask_assistant/__init__.py", line 9, in <module>
    from .core import (
  File "/home/opqrstu/anaconda3/lib/python3.5/site-packages/flask_assistant/core.py", line 12, in <module>
    from .api_ai import ApiAi
ImportError: No module named 'flask_assistant.api_ai'

 So, I checked the directory(~/anaconda3/lib/python3.5/site-packages/flask_assistant/) and then I couldn't find 'api_ai' directory.
 I copied 'api_ai' folder from this repository, pasted it in my directory. and then it worked.

**Comment by treethought** [comment]
thanks for bringing this up. Try reinstalling from pip. Should work without needing to copy the folder now

**Comment by rossmc7** [comment]
I also had this issue when installing 2 days ago, but I just did a fresh install from pip and it worked fine. 

Please let us know if you are still having problems

**Comment by opqrstu** [comment]
No, There are no more problem about it.
I reintalled it and it worked well.
Thanks.

**Comment by opqrstu** [comment]
Oh, I got another issue.
I wanted to control raspberry pi. So I ran my code on raspbian. But it was stucked because of import error.

> Traceback (most recent call last):
  File "my_assistant.py", line 2, in <module>
    from flask_assistant import Assistant, tell
  File "/usr/local/lib/python2.7/dist-packages/flask_assistant/__init__.py", line 9, in <module>
    from .core import (
  File "/usr/local/lib/python2.7/dist-packages/flask_assistant/core.py", line 10, in <module>
    from .response import _Response
  File "/usr/local/lib/python2.7/dist-packages/flask_assistant/response.py", line 2, in <module>
    from . import core
ImportError: cannot import name core

I don't know what I should do.. can you give some advise?

**Comment by rossmc7** [comment]
can you run pip freeze, and paste the output here? That error can happen when you don't have all of the dependencies

**Comment by opqrstu** [comment]
Here:

> Flask==0.10.1
Flask-Ask==0.8.5
Flask-Assistant==0.1.1
Jinja2==2.7.3
MarkupSafe==0.23
Pillow==2.6.1
PyYAML==3.12
RPi.GPIO==0.6.3
RTIMULib==7.2.1
Werkzeug==0.9.6
aniso8601==1.2.0
argparse==1.2.1
blinker==1.3
chardet==2.3.0
colorama==0.3.2
decorator==3.4.0
gpiozero==1.3.1
html5lib==0.999
ipython==2.3.0
itsdangerous==0.24
lxkeymap==0.1
mcpi==0.1.1
ndg-httpsclient==0.3.2
numpy==1.8.2
pexpect==3.2
picamera==1.12
picraft==1.0
pifacecommon==4.2.1
pifacedigitalio==3.1.0
pigpio==1.30
pyOpenSSL==0.13.1
pyasn1==0.1.7
pygame==1.9.2a0
pygobject==3.14.0
pyinotify==0.9.4
pyserial==2.6
python-apt==0.9.3.12
python-dateutil==2.6.0
requests==2.4.3
sense-emu==1.0
sense-hat==2.2.0
simplegeneric==0.8.1
six==1.8.0
smbus==1.1
spidev==3.0
twython==3.1.2
urllib3==1.9.1
wheel==0.24.0
wsgiref==0.1.2

**Comment by rossmc7** [comment]
Looks like you don't have all the required dependencies,  notability cryptography, try installing again and double check any errors you might have.

**Comment by treethought** [comment]
I think it's bc your running python 2. Try running it with python 3.  I'll
try to make it 2-compatible when I get the chance

**Comment by opqrstu** [comment]
First of all, thanks for all advice.
I had tried python3.4.3 already. However, It hadn't worked.
So I tried installing python3.5.2 and it worked well.
I tested a 'hello_world.py' example.
Thanks all again!
