### ISSUE TITLE
install failing in virtualenvironmet

### ISSUE THREAD

**Issue by sharkwheels** [treethought/flask-assistant#22]
Hi. I'm getting this error when trying to install in a virtual environment: `Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j4/h1bl7sdn54qgg21hfwr974l40000gn/T/pip-build-h0o9zgpp/ruamel.yaml/`

Any suggestions on how to troubleshoot this? Preferably without running as sudo? I have the latest pip and updated my setuptools. The virtual environment is running Python 3.5.0 on OSX 10.11.6

Thank you!

**Comment by treethought** [comment]
Interesting. I'm getting this on multiple versions of python 3 on macOS and at least 3.5.2 on linux. However, I don't get the error on macOS 2.7.

The error occurs within ruamel.yaml (external library), however the frozen version (0.13.14) worked previously. So perhaps this is an issue with pip/setuptools?

Thanks for bringing this up. I'll try to look into it.

**Comment by treethought** [comment]
Opened an issue with ruamel.yaml.  https://bitbucket.org/ruamel/yaml/issues/131/pip-installation-fails-on-macos#comment-None

**Comment by sharkwheels** [comment]
Just an update, I went to read the rumel.yaml thread, and was checking around to see if wheel existed in my virtual environments, but it did not. 

I went and installed wheel, and this cleared up the install error for both a virtualenv running python 3.5.0 and 2.7

**Comment by treethought** [comment]
This was resolved by the owner of ruamel.yaml.  try installing the latest version of flask-assistant
`pip install -U flask-assistant`
