### ISSUE TITLE
API.AI setup

### ISSUE THREAD

**Issue by devashish-khatwani** [treethought/flask-assistant#24]
Hey, I am new to Google Home Actions and API.AI. Could you please tell me how to set up API.AI for the Helloworld sample to work. When I run the code in the sample, I get the following warning.

"No API.AI Developer Access Token set.\n                You will not be able to register or retrieve resources from API.AI"
"No API.AI Client Access Token set. You will be able to query the agent"
WARNING:
                No route was provided for the Assistant object, but a flask `app` object given
                The Assistant will be mapped to the app's '/' endpoint.
                If this is a problem please initialize the Assitant with the 'route' parameter

**Comment by sriramsv** [comment]
You need to set the CLIENT_ACCESS_TOKEN and DEV_ACCESS_TOKEN env variables for flask_assistant to pick up

**Comment by devashish-khatwani** [comment]
Thanks for the response, could you tell me how to set environment variable on Windows 10. I tried using the advanced settings and set a variable names as you suggested but it did not work. I was able to create a work around by importing os and setting os.environ['CLIENT_ACCESS_TOKEN'] and os.environ['DEV_ACCESS_TOKEN'] in the code.

**Comment by treethought** [comment]
setting the environment variables using `os.environ` will work, but you wouldn't want to do that with the actual tokens as strings. If you want to keep your tokens private (always a good idea), you could simply store them in a separate .py file and import them to be used with `os.environ`.

I'm not too familiar with windows, so Im not sure how you would set them if that standard way isn't working.

**Comment by treethought** [comment]
Also, are you just running the code without visiting the API.AI web console?  Before running the code you're going to need to create an agent with API.AI.  
Try checking out the 
[Quick start](http://flask-assistant.readthedocs.io/en/latest/quick_start.html) tutorial for a walk through. 


_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by devashish-khatwani** [comment]
I created the API.AI agent but had to manually configure the intents and entities for the HelloWorld example to work  as I was not able to set up the Windows environment variables to run the schema command line utility. I was able to get it to work though. Yup, I created a separate file for configuring the environment variables. Feel free to close the issue, I would reach out to you if I figure out how to set Windows environment variables and you can possibly include it in the Read Me section.

**Comment by treethought** [comment]
sounds good, yeah let me know if you find a solution
