### ISSUE TITLE
Triggering functions from a scheduler? 

### ISSUE THREAD

**Issue by sharkwheels** [treethought/flask-assistant#27]
How does one go about using Flask's app_context w/ flask-assistant? I'm trying to trigger a function on a scheduler. So w/ flask I can wrap the scheduler job in with app.app_context(): and trigger functions (that might be horrible). 

But from an extension like flask-assistant? Not sure. Posted over on stackoverflow, figured I'd ask here too. Though this might be the complete wrong way to go about it. 

https://stackoverflow.com/questions/45132878/trigger-a-function-inside-flask-assistant

**Comment by sriramsv** [comment]
Scheduling jobs should no where be related to flask-assistant, have an API which does the scheduling work for you and use flask-assistant to call the API to do it via your bot.

**Comment by treethought** [comment]
I agree with @sriramsv, this seems to be outside the scope of flask-assistant. The action functions are triggered via requests from API.ai and return a response formatted for API.ai to accept.

So even if you did schedule the action function to trigger, the result wouldn't "go anywhere" if that makes sense. As @sriramsv hinted, you may want to schedule some function to make a call to your API.ai agent which would then make a request to your flask-assistant app.

These [docs](https://api.ai/docs/reference/agent/query) will help if you go that route

**Comment by sharkwheels** [comment]
Hmm. Ok. Thanks for the input! I will follow up w/ those other docs.

**Comment by treethought** [comment]
also, this [module](https://github.com/treethought/flask-assistant/blob/master/api_ai/api.py) will get you going quickly with querying your API.ai agent.  just initialize an `ApiAi`  instance with your client and dev tokens and call the `post_query` method.

**Comment by sriramsv** [comment]
@sharkwheels you can still use your webhook to schedule the job for you, given that you have some other server handling the job schedule functions..
