### ISSUE TITLE
Asking for User Location and Name 

### ISSUE THREAD

**Issue by devashish-khatwani** [treethought/flask-assistant#28]
I have been working with the package and so far it has been very helpful for building quick prototypes. Given my limited programming background it works out perfect. I am now thinking of using some more advanced features such as asking user permission for location and name.  I can solve it trivially by asking for user address and name in an intent but is there a way of getting device location and account name?

**Comment by treethought** [comment]
Glad to hear the library has been helpful! There was actually a recent pull request for asking for permissions for google user data. check out #19. 
I actually haven't had the chance to use it myself but you should be able to return a `permission` response. This response type accepts a list of permissions and context (reasons you want the permission)
```
return permission(['DEVICE_PRECISE_LOCATION'], context='To know where you are')
```

**Comment by abhi007tyagi** [comment]
`return permission(['DEVICE_PRECISE_LOCATION'], context='To know where you are')`
didn't worked 

`ask_permission = permission(['DEVICE_PRECISE_LOCATION', 'NAME'])`
`return str(ask_permission._response)`

worked

**Comment by treethought** [comment]
thanks @abhi007tyagi, appreciate the info. I should have a fix soon. I'm working on migrating to the Actions V2 api
