### ISSUE TITLE
Adding Bot Router Logic

### ISSUE THREAD

**Issue by sriramsv** [treethought/flask-assistant#29]
Hey, this is more an idea rather than an issue with flask-assistant, is there a possibility  where flask-assistant can have a bot router which can route requests with context and user session information to different agents in API.AI? 
It  would be very helpful to query different agents using a single webhook

**Comment by treethought** [comment]
You could do this with flask [blueprints](http://flask.pocoo.org/docs/0.12/blueprints/). I've yet to update the documentation, but you would initialize each agent as a blueprint like so:


```
# project/assistant_1/webhook.py

from flask import Blueprint
from flask_assistant import Assistant

blueprint = Blueprint('assist', __name__, url_prefix='/assist')
assist = Assistant(blueprint=blueprint)
```

```
# project/assistant_2/webhook.py

from flask import Blueprint
from flask_assistant import Assistant

blueprint = Blueprint('assist_2', __name__, url_prefix='/assist_2')
assist = Assistant(blueprint=blueprint)
```

then in app.py or wherever your flask app is created:

```
# project/app.py

from project import assistant_1, assistant_2

app = Flask(__name__)
register_blueprints(app)

def register_blueprints(app):
    app.register_blueprint(assistant_1.webhook.blueprint)
    app.register_blueprint(assistant_2.webhook.blueprint)
```

For each assistant object, you would just point API.AI to the url_prefix given to desired blueprint.
Agent 1 --> https://6e996943.ngrok.io/assist
Agent 2 --> https://6e996943.ngrok.io/assist_2

**Comment by treethought** [comment]
you can check out this [cookie-cutter ](https://github.com/treethought/cookiecutter-flask-assistant) if you need help with the overall application factory structure

**Comment by sriramsv** [comment]
@treethought  yeah this makes lot of sense, but different agents in API.AI use a different user and dev token, then each agent needs to have an corresponding assistant object on the webhook side.

**Comment by treethought** [comment]
excellent point, I should have thought about that.

The method I showed would provide each agent its own assistant object (initialized with its own blueprint) and I believe API.AI would be able to call each one properly using different sessionIDs. However you wouldn't be able to update entities or intent schema from the command line.

I'm thinking a solution would be pretty doable using flask's config object, rather than setting environment variables. I'll try to look into it in the next few days

**Comment by sriramsv** [comment]
@treethought, any traction on this one?

**Comment by treethought** [comment]
Hey @sriramsv, sorry I haven't been able to take a crack at this yet.

**Comment by sriramsv** [comment]
@treethought i did something with this..
https://github.com/sriramsv/api-ai-router

**Comment by treethought** [comment]
nicely done @sriramsv. Looks great!

**Comment by sriramsv** [comment]
@treethought  https://github.com/treethought/flask-assistant/pull/50
