### ISSUE TITLE
More detailed instructions.

### ISSUE THREAD

**Issue by kylefrost** [treethought/flask-assistant#3]
Hello!
This project looks awesome, but I feel a little lost. I've never used API.AI, and don't understand where the Google Developer Console project comes into the equation for getting this to work with Google Home. I've got a good knowledge of Python, etc, but some more detailed instructions on how to set up the API.AI and Google Developer Console portions would be greatly appreciated.
Thanks!

**Comment by rossmc7** [comment]
Hi, 

I am currently working on adding a bit more to the docs, I am about to submit a PR to Treethought. 

But if you could have a look at this, and let me know if anything isn't clear that would be beneficial for both of us.  https://github.com/rossmc7/flask-assistant/blob/master/docs/source/quick_start.rst

Regarding the actual docs on Google Home integration working on that now

**Comment by treethought** [comment]
Thanks for your interest @kylefrost. The docs are a little incomplete right now, but I'm working on making them more comprehensive to get users started quickly. 

The general idea is that you create intents and define 'user says' phrases within the API console, and when those intents are triggered API.AI makes a call to your flask-assistant webhook. These intents are triggered based on the user says phrases.

Intents may also require user-defined entities (types of parameters) if they are more complex and require parameters from the user that aren't defined within API.AI's own entities.

I'm working on support for your assistant app to automatically register the intents, what the user says to trigger them, and the types (entities) of parameters the intents accept within the api console. When this is complete it will be a lot easier and much quicker to set up your app than using API's web interface. It should be ready pretty soon.

It might be a little buggy, but with the current version on pip you can use the [schema](http://flask-assistant.readthedocs.io/en/latest/generate_schema.html) terminal command to automatically register intents from your app.

**Comment by treethought** [comment]
I've provided a more complete quick start [guide](http://flask-assistant.readthedocs.io/en/latest/quick_start.html) in the docs. Let me know if theres still anything your unclear about.

I provided a link at the end of the guide to API.AI's instructions on integrating with Actions/Google Home. One your all set up on API, its only a few steps to preview on the Home.
