### ISSUE TITLE
Ability to do some stuff on every incoming request to the webhook

### ISSUE THREAD

**Issue by sriramsv** [treethought/flask-assistant#32]
Hey @treethought , I am not able to figure out how I can do some stuff such as logging on a global level on each incoming POST request to the webhook. It would be great if you can add that feature.

**Comment by treethought** [comment]
Hey @srirams, sorry for such a late response. Have you seen Flask's [request callbacks](http://flask.pocoo.org/docs/0.12/patterns/deferredcallbacks/)?
