### ISSUE TITLE
Making an entity 'anything'?

### ISSUE THREAD

**Issue by hkyq** [treethought/flask-assistant#34]
Say I have this: 

```
from flask import Flask
from flask_assistant import Assistant, ask, tell

app = Flask(__name__)
assist = Assistant(app, '/')

@assist.action("say-hello")
def say_hello(name):
    return ask('Hello, {}'.format(name))

if __name__ == '__main__':
    app.run(debug=True)
```
How could I edit my entities.yaml file to make name be 'anything', as I won't know the users name.

**Comment by hkyq** [comment]
UPDATE: I changed it to this:
```

from flask import Flask
from flask_assistant import Assistant, ask, tell

app = Flask(__name__)
assist = Assistant(app, '/')

@assist.action("say-hello")
def say_hello():
    return ask('Hello. Test successful.')

if __name__ == '__main__':
    app.run(debug=True)
```
And this config:

https://gyazo.com/1d5b1e7c609a8c96abf814350e19b87f

When I say 'testing testing' in the console to the right, it works. But when I say 'Ok Google, testing testing' to my Google Assistant, I'm given the default reply. My Google Home is integrated.

**Comment by hkyq** [comment]
UPDATE 2:
So I got it to work (didn't know about the test app stuff) however I got a 'Sorry, I can't get the test app's response' or something, when attempting to say my trigger word. I thought that was weird so I added a default response through the web panel at api.ai. I said the triggerword again, and then I got the response on which I put in my web panel. Why is the default response in the script not working?

**Comment by treethought** [comment]
Hey @hkyq. In regards to your initial question, you'll likely want to use API.Ai's [system entities](http://flask-assistant.readthedocs.io/en/latest/parameters.html#mapping-parameters-to-api-ai-system-entities) for cases like that. For names you can use @sys.given-name entity.

As for second question, if you remove the 'testing complete'  from the api.ai console and use the console (not google home) to trigger it do you get a response?
