### ISSUE TITLE
Context Issues

### ISSUE THREAD

**Issue by rajasaur** [treethought/flask-assistant#35]
It looks like flask-assistant uses Contexts using its own library (managed in core.py) rather than that of the one used by api.ai.. Although this seems okay initially, I have come across cases where this causes issues and makes it quite hard to use.

For e.g. If I have a "yes" or "no" response for a question that will only need to be received upon a particular intent being hit, I cant do that because api.ai seems to be sending it anyway to the webhook since there are no contexts defined. Inside core.py, it seems to be checking if there are any view_funcs that match the output and if there arent any, it just returns the first function configured (Line 291: core.py) . Im expecting the "Default fallback intent" to get fired in this case because the required primary intent has not been hit yet, but a subsequent followup is being picked up.

Is there a better way of handling this?

My usecase is a workflow asking the end-users a series of yes/no questions. Without context, this is just picking up the first method that response to a "yes" or "no". (Based on my above description)

Pls let know if you need any more information about my usecase.

**Comment by treethought** [comment]
Hey @rajasaur. Are you familiar with api.ai's [folluw-up intents](https://api.ai/docs/intents#follow-up_intents) and [events](https://api.ai/docs/events)?These may to be a better match for your situation than alternating/stacking different contexts for the series of questions.

Events simply allow you to basically call another intent from within your action, while followups are intents that are triggered directly after a given intent. You can define both events and followups in the api.ai console, but currently not from flask-assistant. (Follow up intents are just events behind the scenes)


You can create 'yes' and 'no' fallback intents as well as custom ones. These can pass entities to your action functions just like regular intents.

Inside your webhook you can use followups like this:

```
@assist.action('AskFries')
def ask_for_fries():
    return ask('Would you like fries with that?')

@assist.action('AskFries - yes')
def ask_to_supersize():
    return ask('Do you want to supersize it?)

@assist.action('AskFries - no')
def answer_for_no():
    return tell('ok, your total is $4')


```

You can also stack followup intents
```
@assist.action('AskFries')
def ask_for_fries():
    return ask('Would you like fries with that?')

@assist.action('AskFries - yes')
def ask_to_supersize():
    return ask('Do you want to supersize it?)

@assist.action('AskFries - yes - yes') # default name created inside API.AI
def finish_order():
    return tell('Nice, ill make them supersized')

@assist.action('AskFries - yes - no') # default name created inside API.AI
def finish_order():
    return tell('ok, one regular fry.')
```

You can change the followup intent's name inside the api.ai console:
```
@assist.action('AskFriesSupersized')  # was 'AskFries - yes'
def ask_followup_question():
    return ask('Do you want to supersize it?)

@assist.action('ConfirmSuperSize')  # instead of 'AskFries - yes - yes'
def finish_order():
    return tell('Nice, ill make them supersized')

@assist.action('ConfirmRegularFry')  # instead of 'AskFries - yes - no'
def finish_order():
    return tell('ok, one regular fry.')
```

 Or use events instead of stacking followups
 ```
 from flask_assistant import ask, tell, event

@assist.action('AskFries')
def ask_for_fries():
    return ask('Would you like fries with that?')

@assist.action('AskFries - yes')
def ask_to_super_fries():
    return event('AskSuperSize')

@assist.action('AskFries - no')
def move_onto_soda():
    return event('AskSoda')

@assist.action('AskSupersize') # Intent has an event defined in console
def ask_to_supersize():
    return ask('Do you want to supersize it?)

# ... follow up intents

@assist.action('AskSoda') # Intent has an event defined in console
def ask_for_soda():
    return ask('Would you like a soda?')

# ... followup intents
```

**Comment by rajasaur** [comment]
Thanks @treethought . I ended up using flask-assistant for the "actions" but defined the contexts directly on the apiai so that they behave properly for my interaction.

Are you planning on introducing contexts from within the flask-assistant at some point. I was thinking of forking this and starting to add contexts because everytime I do a schema <myhook>.py, all the info that I entered on the apiai console are gone and have to redo it, which isnt fun when you have > 10 intents.

**Comment by treethought** [comment]
glad to hear you got it working, sorry for my late response.

There is a reason for the current implementation as you saw in #8,  and your contexts should work correctly even if not defined in the console when using the `context_manager`. This does seem to cause confusion though, so I think I'll try to get the  workflow to match API.ai soon.

I'l try to get it implemented sometime this week, but you're welcome to submit a PR yourself. If you do fork it, let me know if you have any questions. and thanks for bringing up the issue!
