### ISSUE TITLE
"ImportError: cannot import name core" when generating schema/intents

### ISSUE THREAD

**Issue by kariudo** [treethought/flask-assistant#5]
Getting the following error when trying to use the intent generation via schema:

> Traceback (most recent call last):
>   File "/usr/local/bin/schema", line 11, in <module>
>     load_entry_point('Flask-Assistant==0.1.1', 'console_scripts', 'schema')()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2642, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2296, in load
>     return self.resolve()
>   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/site-packages/api_ai/cli.py", line 5, in <module>
>     from flask_assistant.core import Assistant
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/__init__.py", line 9, in <module>
>     from .core import (
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/core.py", line 10, in <module>
>     from .response import _Response
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/response.py", line 2, in <module>
>     from . import core
> ImportError: cannot import name core

**Comment by kariudo** [comment]
Looks like I get a similar error when trying to run the script itself as well:

> Traceback (most recent call last):
>   File "./testAssistant.py", line 2, in <module>
>     from flask_assistant import Assistant, tell
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/__init__.py", line 9, in <module>
>     from .core import (
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/core.py", line 10, in <module>
>     from .response import _Response
>   File "/usr/local/lib/python2.7/site-packages/flask_assistant/response.py", line 2, in <module>
>     from . import core
> ImportError: cannot import name core

**Comment by treethought** [comment]
Try using python 3, rather than 2.7. I'll try to provide compatibility for
2 when I get the chance. I'll also be providing an update to provide more
complete scheme generation soon

**Comment by kariudo** [comment]
Same issue with just starting the script:

> Traceback (most recent call last):
>   File "./testAssistant.py", line 2, in <module>
>     from flask_assistant import Assistant, tell, ask
>   File "/Users/kariudo/Code/py/plexAssistant/venv/lib/python2.7/site-packages/flask_assistant/__init__.py", line 9, in <module>
>     from .core import (
>   File "/Users/kariudo/Code/py/plexAssistant/venv/lib/python2.7/site-packages/flask_assistant/core.py", line 10, in <module>
>     from .response import _Response
>   File "/Users/kariudo/Code/py/plexAssistant/venv/lib/python2.7/site-packages/flask_assistant/response.py", line 2, in <module>
>     from . import core
> ImportError: cannot import name core

To be on the safe side I tried it with a clean virtualenv on 2.7.13 with no global site packages and installed just flask-assistant with pip, same result.

**Comment by treethought** [comment]
Ya this is a problem with the how modules are imported in python 2 vs
python 3.
If you use a virtualenv with python 3 it should work.

**Comment by kariudo** [comment]
That was it. Didn't see anywhere that said py3 was required (probably should somewhere). Thanks, I'll close this issue.
