### ISSUE TITLE
is there a way to check the source of the user input

### ISSUE THREAD

**Issue by chaoranxie** [treethought/flask-assistant#54]
i would like to know if the intent is being trigger by "google-assistant" app or text via twillio integration. 

The reason I would like to know the source is so i can customize the output. If it is google-assistant i will use less text in "ask" and use suggest, but if intent is trigger via text, i would like to add more text in the "ask" method since there is no suggest or card

**Comment by treethought** [comment]
This info can be found in the `request` object explained in #52

**Comment by chaoranxie** [comment]
Thanks @treethought.
```
request['originalRequest']['source'] -> twilio
request['originalRequest']['source'] -> google
```
