### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by newone16** [treethought/flask-assistant#55]
Hi, 

I have copied the templates folder and webhook.py under samples/hass, when I tried to perform $schema webhook.py, I get the below pasted error. 
---------------
Generating intent schema...
Traceback (most recent call last):
 
    re_value = r".\b{}\b".format(value[1:]) if value.startswith(('$', '¥', '￥', '€', '£')) else r"\b{}\b".format(value)
AttributeError: 'int' object has no attribute 'startswith'
---------------

But if I comment these 2 lines from user_says.yaml 
turn-on-light:
  UserSays:
  - turn on the fan
  - turn on the lamp to 100 percent
  - turn on fan to 50 brightness
  Annotations:
  - fan: light
  - lamp: light
  - lights: light
  #- 100: brightness
  #- 50: brightness

Then it works fine.

Thanks for the help.

**Comment by robwilkes** [comment]
Hi, if you put the two numbers into quotations, to treat them as a string, it will work. ie:
- '100': brightness
- '50': brightness

**Comment by robwilkes** [comment]
@newone16 please try again now. it should be resolved in the latest commit without the need to enclose number in quotes.

**Comment by newone16** [comment]
Thanks a lot works fine :)

**Comment by newone16** [comment]
Although the schema generation is working without error - usersays details are not populated in the json @robwilkes - could you pls check
