### ISSUE TITLE
Quickstart problems?

### ISSUE THREAD

**Issue by dementedhedgehog** [treethought/flask-assistant#59]
Newbie.. so take these with a grain of salt..on this page
http://flask-assistant.readthedocs.io/en/latest/quick_start.html#testing-the-assistant

i) Had to export CLIENT_ACCESS_TOKEN to make it stop complaining?
ii) In the code you have
@assist.action("user-gender")
def ask_for_color(gender):

But in the yaml you have:  user-gives-gender: ??  I had to change that to make it work?
iii)  if gender is 'male': should be  if gender == 'male':  ??

Nice work!  Thanks for sharing.

**Comment by treethought** [comment]
Thanks for pointing these out , update the guide. 👍

**Comment by treethought** [comment]
Changes made in https://github.com/treethought/flask-assistant/commit/a17bc5c46cf2920e5af06d50502434574d29ad9d
