### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by sudermanjr** [treethought/flask-assistant#60]
I have been able to get this working with Slack, but everything is one-way right now.  I am guessing that a new action would need to be added to send to the slack webhook instead of google assistant, but I am not sure.

How hard would it be to do this?

**Comment by treethought** [comment]
Hey @sudermanjr, what do you mean by one-way? It would be possible to set up a slack webhook, but Dialogflow should handle the integration sufficiently. Would you mind explaining your issue a bit more?

**Comment by sudermanjr** [comment]
When I tested it out, I was able to send messages to the dialogflow api, and my server received them, but no responses came through to slack.  

The app works great through voice, and the google assistant responds perfectly.

**Comment by treethought** [comment]
Do you see a response in the Dialogflow console when sending a message from inside the console?
