### ISSUE TITLE
“User Says” examples not being published to console

### ISSUE THREAD

**Issue by flyinactor91** [treethought/flask-assistant#61]
Went through the QuickStart. After a successful run of “schema app.py” (with the changes noted in #59), the DialogueFlow console is populated with everything except the user utterances. Once they are typed in manually from the schema into the console, the app works as expected.

**Comment by treethought** [comment]
Did you receive any error? It's possible you may have tried to push the intents to the console before filling out the template. You could try re-running the schema command or if that doesnb't work delete the intents in the console and try again. Let me know if the issue persists
