### ISSUE TITLE
Converstation End

### ISSUE THREAD

**Issue by msghaleb** [treethought/flask-assistant#70]
Great project and great work!
I'm new to the topic, how can I end a conversation? I created a function but what should I use a "return" to exit the app? using the "Set this intent as end of conversation" on API AI makes the app hangs. 

Any help is much appreciated.

**Comment by msghaleb** [comment]
I used this and it seems to work (sometimes)

@assist.action('end-converstation')
def end_of_converstation():
    speech = "Ok, as you like. See you later"
    return tell(speech)

**Comment by robwilkes** [comment]
Hi Mohamed,

Do you mean to end the dialogue with the user?

It's in the documentation, under primary types, you 'tell' the user
something rather than 'ask' (and wait for a response).

https://flask-assistant.readthedocs.io/en/latest/responses.html#primary-types

**Comment by msghaleb** [comment]
Hi Robwilkes,

thanks for the quick answer, got it! works great!

Thank you
