### ISSUE TITLE
ngrok question

### ISSUE THREAD

**Issue by msghaleb** [treethought/flask-assistant#71]
Hi,

I've used the quick start guide and so far worked great! using ngrok.

Do you have best practice if I want to put this in a container? let's say in AWS or Azure? with Public IP.

I won't need ngrok I assume, right? but also http://CONTAINER_IP:5000 will probably not work well 

Any guidance is much appreciated.

Thank you

**Comment by treethought** [comment]
Hey @msghaleb, you would follow the same process of setting up the webhook for DIalogflow as with ngrok. You just need to expose a public URL to your webhook, initialize the Assistant object with the endpoint (defaults to "/"), and I believe the URL also needs to be https.

While using an IP address may be possible, I have a feeling specifying a port won't work with Dialogflow's API.

**Comment by msghaleb** [comment]
Hi @treethought great, I've got it working using a container in Azure however I had to point the app.run function to listen on 0.0.0.0 as it does listen only on localhost (may be worthy adding to the Documentation?) --> app.run(debug=True, host='0.0.0.0')

Also the URL http://xxx.xxx.xxx.xxx:5000 worked well from the API AI.

Now I will get a certificate and get it working on https.

Again many thanks for the great work!!

**Comment by robwilkes** [comment]
HTTPS won't work with an IP, the certificate won't validate (you can't get
a certificate for an IP), it needs to be backed by DNS, and yes I think
HTTPS is required, so you will need a domain, FQDN, exposed public IP, and
valid SSL certificate, to name just a few things.

Our you could use ngrok within AWS, which solves most of those but means
you're relying on a third party.

**Comment by treethought** [comment]
@msghaleb No problem thanks for bringing up the issue! 

This isn't discussed in the documentation, as it is a general flask issue, but running the app via `app.run(debug=True)` should only be used for local/development. It uses flask's built in server and is not secure and can only handle one request at a time. 

Check out flask's [deployment documentation](http://flask.pocoo.org/docs/0.12/deploying/). The options described there should also help get an idea of how to get a public URL for your webhook (heroku is very easy to set up).

**Comment by msghaleb** [comment]
Hi robwilkes, yep I'll have to get a DNS name. Don't you think I can use Werkzeug for that? (at least for proofing the concept?)

Didn't test it yet, but will something like that work? 

if __name__ == "__main__":
    context = ('cert.crt', 'key.key')
    app.run(host='0.0.0.0', port=443, ssl_context=context, threaded=True, debug=True)

ref: http://werkzeug.pocoo.org/docs/0.14/serving/
