### ISSUE TITLE
yaml formatting

### ISSUE THREAD

**Issue by chew-z** [treethought/flask-assistant#76]
This isn't issue per se with flask-assistant but friendly warning to fellow chatbot builders. flask-assistant and underlying libraries will quietly skip entire parts due to some odd space and wrong indent in yaml files. 

In my case entire parts of _user says_ had been empty and suddenly your chatbot will get dumb and unable to recognize phraes that had been working just minutes before. Very frustrating and you could waste hours.

So when in doubt check intents and entities  in Dialogflow console or inspect json files in _schema_ folder. And get proper yaml formatter for your editor.

On a positive note perhaps a little more verbose out from ```schema``` command will help.

**Comment by treethought** [comment]
Thanks for the warning @chew-z. Perhaps more verbosity from `schema` could be added.
