### ISSUE TITLE
Contexts

### ISSUE THREAD

**Issue by ovidiuMaier** [treethought/flask-assistant#8]
Hi! First of all thanks for providing this. It's a great tool for quickly getting up and running.

I seem to have an issue with the contexts or maybe I don't understand how you intended them to be used.
The intents.json always has "contexts" and "affectedContexts" void for me. Is there a way to define the input/output contexts using flask-assistant? 

The problem is that even if I:
- define the input and output contexts in the API.AI console
- and then later add another entry in the user_says.yaml 
- run the schema command 
- the previously defined contexts get deleted, as the intents.json contains no contexts.

Would love your input on this if you have time, thanks

**Comment by treethought** [comment]
Hey, thanks for bringing this up.

So the way it is set up currently, contexts are never actually registered with api.ai. Instead they are used only within your code to help flask-assistant match the appropriate action function for the triggered intent. 

The reason for this was to allow defining multiple action functions for the same intent, and have the correct action matched based on the contexts that are present, as shown in the docs.
However this is different than [API.AI's way](b878b7801aa2488bb869307469be7aeb), where each intent has a single defined set of required contexts and so registering contexts with intents wouldn't work correctly. Unfortunately, this causes your contexts declared in the console to be overwritten as None.

For now if you don't define the contexts in the console, but use them in your code it should work as expected, and you will still see active contexts while testing. But I think I will change the way contexts are implemented to more aligned with API.AI's method.

**Comment by ovidiuMaier** [comment]
That's great, thanks for the quick response!

**Comment by rajasaur** [comment]
Hi @treethought , I was wondering if you started building the contexts as per API.AI. Im going to try and work on making this work from the webhook (i.e. pass the contexts from the flask handlers), so just wanted to check if you already started this. Thanks!
