### ISSUE TITLE
Alternatives to Ngrok?

### ISSUE THREAD

**Issue by mayo-man** [treethought/flask-assistant#88]
Does anyone know a good alternative to Ngrok for a forwarding URL (must be https not http) that works well? Something that's permanent and I can host myself?

**Comment by treethought** [comment]
I'm unaware of any alternatives, however ngrok let's you use a custom domain but I believe it requires a paid account

https://ngrok.com/docs

> ngrok assigns random hexadecimal names to the HTTP tunnels it opens for you. This is okay for one-time personal uses. But if you're displaying the URL at a hackathon or integrating with a third-party webhook, it can be frustrating if the tunnel name changes or is difficult to read. You can specify a custom subdomain for your tunnel URL with the -subdomain switch.

**Comment by treethought** [comment]
closing this for now as it is not directly related to flask-assistant
