### ISSUE TITLE
function to get the current api.ai entities 

### ISSUE THREAD

**Issue by sriramsv** [treethought/flask-assistant#9]
There is no way I can get the entities already defined in api.ai currently, it would be useful to get the list of entity objects, especially when the backend logic needs to have the same state variables

**Comment by treethought** [comment]
That would be useful. I'll get started on that, hopefully have it soon.

**Comment by treethought** [comment]
You should now be able to get the entities and intents registered in API.AI.

Given an Assistant object "assist", they are accessed at `assist.api.agent_entities` and `assist.api.agent_intents`.

**Comment by sriramsv** [comment]
awesome.. Thanks for getting this out like a flash.
Closing this issue
