### ISSUE TITLE
Card with Image

### ISSUE THREAD

**Issue by kaiserkumars** [treethought/flask-assistant#92]
When I try to display a card with image like this one below:
**return tell("The result is").card(text="Some text",title='Some title',img_alt="Some text",img_url=some_img_url)**
I get the **MalformedResponse** Error in the simulator:
**final_response.rich_response: the first element must be a 'simple_response', a 'structured_response' or a 'custom_response'.**

**Comment by gmolau** [comment]
Is it possible that the string that you passed to tell() was None?

**Comment by kaiserkumars** [comment]
Ok, my bad! I forgot to enable Actions on Google Integration. Just had to add this in my code:
**app.config['ASSIST_ACTIONS_ON_GOOGLE'] = True**
