### ISSUE TITLE
MalformedResponse error when no image is used and no way to provide accessibility_text

### ISSUE THREAD

**Issue by 1337Phantom** [treethought/flask-assistant#95]
`app.config['ASSIST_ACTIONS_ON_GOOGLE'] = True`

`return tell('fullName').card(title='Hello', text='text')`
This gives the error as 

> MalformedResponse at final_response.rich_response.items[1].basic_card.image: the protocol must be 
http or https

> MalformedResponse
> final_response.rich_response.items[1].basic_card.image: 'accessibility_text' is required.
 

When you do give an image
`return tell('fullName').card(title='Hello', text='text',img_url='https://example.com/a.png')`

This is the only error remaining
> MalformedResponse
> final_response.rich_response.items[1].basic_card.image: 'accessibility_text' is required.

Thanks a lot

**Comment by gmolau** [comment]
You can specify the accessibility text with the [`img_alt`](https://github.com/treethought/flask-assistant/blob/262791f1b3bb7e8787f46714569c76ea18771dd1/flask_assistant/response.py#L99) attribute.

**Comment by 1337Phantom** [comment]
Thanks @gmolau I got it to stop throwing errors but it is still not showing the card. It only displays the string in the tell function, in my case, it is "fullName".  And also I'm unable to respond without an image.

Thanks a lot to both @gmolau and @treethought

**Comment by gmolau** [comment]
If you did it like in your first message that is how it should work, if it doesn't you'd have to provide more context (code and Google Actions log and/or screenshots).

**Comment by 1337Phantom** [comment]
I got it to work on my phone. Turns out that it doesn't show up on the simulator but works on the actual device.
Thank you @gmolau
