### ISSUE TITLE
Can't post request to google action via ngrok - "POST / HTTP/1.1" 500

### ISSUE THREAD

**Issue by Nitinvermaa** [treethought/flask-assistant#96]
I tried with sample code as per documentation.

from flask import Flask
from flask_assistant import Assistant, ask, tell

app = Flask(__name__)
assist = Assistant(app, route='/')

@assist.action('greeting')
def greet_and_start():
    speech = "Hey! Are you male or female?"
    return ask(speech)

if __name__ == '__main__':
    app.run(debug=True)

Also created a intent in Dialogflow and enabled webhook call for this intent. But when i executed the above mentioned code, I got error as --- 

C:\Users\my_assistant>python webhook.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 100-171-257
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [03/Jun/2018 02:36:20] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AppData\Local\Programs\Python\Python36-32\lib\site-packages\flask_assistant\core.py", line 275, in _flask_assitant_view_func
    self.intent = self.request['result']['metadata']['intentName']
KeyError: 'result'

ngrok log:
Session Status                online
Session Expires               7 hours, 23 minutes
Version                       2.2.8
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://a65bdf81.ngrok.io -> localhost:5000
Forwarding                    https://a65bdf81.ngrok.io -> localhost:5000

Connections                   ttl     opn     rt1     rt5     p50     p90
                              5       0       0.00    0.00    0.34    0.4

HTTP Requests
-------------

POST /                         500 INTERNAL SERVER ERROR
POST /                         500 INTERNAL SERVER ERROR

Please help me to resolve this issue.

**Comment by Nitinvermaa** [comment]
Forgot to add 'Action on Google  response log:
{
  "responseMetadata": {
    "status": {
      "code": 10,
      "message": "Failed to parse Dialogflow response into AppResponse because of empty speech response",
      "details": [
        {
          "@type": "type.googleapis.com/google.protobuf.Value",
          "value": "{\"id\":\"3e437d4e-7a9e-45d2-8c19-474c53173535\",\"timestamp\":\"2018-06-02T21:37:07.752Z\",\"lang\":\"en-in\",\"result\":{},\"status\":{\"code\":206,\"errorType\":\"partial_content\",\"errorDetails\":\"Webhook call failed. Error: 500 INTERNAL SERVER ERROR\"},\"sessionId\":\"1527975400470\"}"
        }
      ]
    }
  }
}

Please help me

**Comment by gmolau** [comment]
Is it possible that your are using V2 of the Dialogflow Webhook (which is now the default)? If yes you'd have to change that to V1 as flask-assistant does not yet support the new version.

**Comment by Nitinvermaa** [comment]
Thanks for your suggestion, problem is been resolved. One last question, how to create and app which display an image or render a video using flask assistant. Can you please share the document link if possible.

Thanks,

**Comment by gmolau** [comment]
The [flask-assistant](http://flask-assistant.readthedocs.io/en/latest/index.html) documentation isn't that long, I'm sure you'll find the "Rendering Responses" section for yourself:)

**Comment by Nitinvermaa** [comment]
Thanks. How increase response timeout. I'm triggering action which will hit an API and  give json with employee name and employeeID, till it return I'm getting session webhook timeout exception.
Below is the error log
{
  "responseMetadata": {
    "status": {
      "code": 10,
      "message": "Failed to parse Dialogflow response into AppResponse because of empty speech response",
      "details": [
        {
          "@type": "type.googleapis.com/google.protobuf.Value",
          "value": "{\"id\":\"c5bb1ed2-8300-4c82-a9d0-7cf77fcd0c86\",\"timestamp\":\"2018-06-04T12:35:53.444Z\",\"lang\":\"en-us\",\"result\":{},\"status\":{\"code\":206,\"errorType\":\"partial_content\",\"errorDetails\":\"Webhook call failed. Error: Request timeout.\"},\"sessionId\":\"1528115736679\"}"
        }
      ]
    }
  }

Is it possible to increase timeout in google flask assistant.
