### ISSUE TITLE
Enhancement: add support for checking SCREEN_OUTPUT

### ISSUE THREAD

**Issue by 1337Phantom** [treethought/flask-assistant#97]
While returning lists we need to be able to check if the user is on a device which has a screen( i.e actions.capability.SCREEN_OUTPUT). 

If the user is on a google home mini he won't be able to get the list in which case the output should be sent via `ask() or tell()`. If such a feature already exists please let me know.

Thank you

**Comment by gmolau** [comment]
This is already possible, see the Actions on Google documentation for [Surface Capabilities](https://developers.google.com/actions/assistant/surface-capabilities).

**Comment by 1337Phantom** [comment]
@gmolau How do I implement this? 
Thanks a lot

**Comment by 1337Phantom** [comment]
This is my code, I was wondering if I could check if the device has a screen and display the list or not depending on the output. 
```
resp = ask("Here are the results")
        mylist = resp.build_list("Which one?")
        i=0
        for names in fullName:
            mylist.add_item(title=names,
                key=names,
                img_url="",
                description=email[i],
                synonyms=synons[i]) 
            i=i+1       
        return mylist
```


Also a small question, how do you handle the response from the user in the case of a list? 

This is my history on DialogFlow:
![capture](https://user-images.githubusercontent.com/37427693/40888451-d7e4015e-6774-11e8-9916-c25b96d358ab.PNG)
Should I create another function to handle that intent?


Again thanks a lot @gmolau, I'm extremely grateful for all the help you and @treethought have provided me.

**Comment by gmolau** [comment]
As you see in the history, selecting a list item triggered an `actions_intent_OPTION` event. Dialogflows [documentation](https://dialogflow.com/docs/events) is very clear on how to handle this.

I don't want to be rude, but it would be better to ask these kinds of questions on StackOverflow, to keep this issue tracker focused on the improvement of the flask-assistant library.
